version: '3'

services:
  otrs:
    image: redeonco/otrs:latest
    build: rede_onco-otrs
  mariadb:
    image: redeonco/otrs-mariadb:latest
    build: rede_onco-otrs_mariadb
# If you need access to the database, uncomment this service
#  adminer:
#      image: adminer:standalone
#      read_only: true
#      volumes:
#        - /tmp
#      ports:
#        - "8080:8080"
#      depends_on:
#        - mariadb
#      links:
#        - mariadb
